In [1]:
import numpy as np

### zeros & ones
- 0으로 채워진 array를 지정한 차원만큼 만들 수있음

In [3]:
zeros = np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
zeros = np.zeros(1)
zeros

array([0.])

In [8]:
zeros = np.zeros([3,3,3])
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

- 1로 채워진 array를 차원만큼 만들 수 있음

In [10]:
ones = np.ones([10,5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
ones * 10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
arr = np.arange(4,9)
arr

array([4, 5, 6, 7, 8])

In [16]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Index

In [19]:
nums = [1,2,3,4,5]
nums

[1, 2, 3, 4, 5]

In [20]:
nums[0]

1

In [21]:
nums[0:3]

[1, 2, 3]

In [22]:
arr[1]

array([3, 4, 5])

### Boolean Indexing

In [26]:
data = np.random.randn(3,3)
data

array([[-0.04395691, -0.61221668,  0.40658022],
       [-1.25169791, -0.54427627, -0.81638717],
       [-0.06590914,  0.65877069,  0.88905796]])

In [27]:
data <=0

array([[ True,  True, False],
       [ True,  True,  True],
       [ True, False, False]])

In [29]:
data[data <=0] =1

In [30]:
data

array([[1.        , 1.        , 0.40658022],
       [1.        , 1.        , 1.        ],
       [1.        , 0.65877069, 0.88905796]])

### Broadcast

In [31]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
arr + np.array([1,1,1])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr = np.array([1,6,3,7,3,2,0,0,2])

In [35]:
arr

array([1, 6, 3, 7, 3, 2, 0, 0, 2])

In [36]:
np.argmax(arr)

3

- np.argmax()
- 가장 큰 값이 있는 인덱스를 보여줌

In [37]:
np.unique(arr)

array([0, 1, 2, 3, 6, 7])

- np.unique()
- 중복되지 않게 값들을 가져옴

In [38]:
arr = np.array([[1,2,3],[1,2,3]])
arr

array([[1, 2, 3],
       [1, 2, 3]])

In [39]:
arr.dtype

dtype('int32')

.astype()으로 datatype을 변환가능

In [40]:
arr.astype(np.int32)

array([[1, 2, 3],
       [1, 2, 3]])

In [41]:
arr.astype(np.float64)

array([[1., 2., 3.],
       [1., 2., 3.]])

In [43]:
arr = np.array([[1.,2,3],[1,2,3]], dtype=np.uint8)

In [44]:
arr

array([[1, 2, 3],
       [1, 2, 3]], dtype=uint8)

In [45]:
arr.dtype

dtype('uint8')

In [46]:
len(arr.shape)

2

In [47]:
len(arr.shape)

2

In [48]:
arr.shape

(2, 3)

In [49]:
arr.reshape([3,2])

array([[1, 2],
       [3, 1],
       [2, 3]], dtype=uint8)

In [56]:
arr = np.random.randint(6,size=(2,3))

In [57]:
arr

array([[2, 3, 0],
       [0, 0, 4]])

### Ravel
- arr의 차원을 1차원으로 바꿔줌

In [58]:
arr.shape

(2, 3)

In [59]:
arr = arr.ravel()

In [60]:
arr.shape

(6,)

In [61]:
arr

array([2, 3, 0, 0, 0, 4])

### np.expand_dims()
- 안의 값은 유지하면서 차원을 늘림

In [62]:
arr.shape

(6,)

In [63]:
arr = np.expand_dims(arr, 0)

In [64]:
arr

array([[2, 3, 0, 0, 0, 4]])

In [65]:
arr.shape

(1, 6)

In [69]:
arr = arr.ravel()

In [70]:
arr.shape

(6,)

In [71]:
arr = np.expand_dims(np.expand_dims(arr, -1),0)

In [72]:
arr.shape

(1, 6, 1)

In [73]:
arr = np.expand_dims(arr, 1)

In [74]:
arr

array([[[[2],
         [3],
         [0],
         [0],
         [0],
         [4]]]])

In [75]:
arr.shape

(1, 1, 6, 1)

In [76]:
arr = np.expand_dims(arr,3)

In [77]:
arr.shape

(1, 1, 6, 1, 1)